[package]
name = "os"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
lazy_static = { git = "https://github.com/rust-lang-nursery/lazy-static.rs", version = "1.5.0", features = [
    "spin_no_std",
] }
buddy_system_allocator = "0.9.0"
riscv = "0.10.1"
linked_list_allocator = "0.10.5"
log = "0.4"
bitflags = "2.0.0"
xmas-elf = "0.9.0"
spin = "0.9.6"
virtio-drivers = "0.1.0"
fat32 = { path = "../fat32" }
