[package]
name = "fat32"
version = "0.0.1"
edition = "2021"

[dependencies]
spin = "0.9.6"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
